import React from "react";
import {
  Bed,
  Box,
  Briefcase,
  DoorOpen,
  Flower2,
  Home,
  Lamp,
  LayoutGrid,
  Library,
  Moon,
  Palmtree,
  Refrigerator,
  ShowerHead,
  Sofa,
  Soup,
  Tv,
  Utensils,
  WashingMachine,
  Waves,
  Dog,
  Car,
  Baby,
  TreePine,
  Brush,
  Zap,
  GlassWater,
  Flame,
  Shirt,
  Scissors,
  Trash2,
  Package,
  Key,
  Shield,
  Lightbulb,
  Music,
  Coffee,
  HardHat,
} from "lucide-react";

export const AVAILABLE_ICONS = {
  Home,
  Soup,
  Sofa,
  ShowerHead,
  Bed,
  Briefcase,
  WashingMachine,
  Dog,
  Car,
  Baby,
  TreePine,
  Brush,
  Zap,
  Utensils,
  GlassWater,
  Refrigerator,
  Flame,
  Shirt,
  Scissors,
  Trash2,
  Package,
  Key,
  Shield,
  Lightbulb,
  Music,
  Tv,
  Coffee,
  HardHat,
  Box,
  DoorOpen,
  Flower2,
  Lamp,
  LayoutGrid,
  Library,
  Moon,
  Palmtree,
  Waves,
} as const;

export type IconName = keyof typeof AVAILABLE_ICONS;

export const ROOM_ICON_MAP: Record<string, React.ElementType> = {
  "Tout l'appartement": Home,
  "Cuisine": Soup,
  "Salon": Sofa,
  "Salle de bain": ShowerHead,
  "Toilettes": Waves,
  "Entrée": DoorOpen,
  "Chambre parentale": Bed,
  "Chambre enfant": Lamp,
  "Bureau": Briefcase,
  "Buanderie": WashingMachine,
  "Balcon": Palmtree,
  "Cave / garage": Box,
  "Chambre": Bed,
  "Salle à manger": Utensils,
  "Jardin": Flower2,
  "Bibliothèque": Library,
  "Cinéma": Tv,
};

export function getRoomIcon(roomName: string | null | undefined, manualIcon?: string | null) {
  if (manualIcon && manualIcon in AVAILABLE_ICONS) {
    return AVAILABLE_ICONS[manualIcon as IconName];
  }
  
  if (!roomName) return LayoutGrid;
  const normalized = roomName.trim();
  return ROOM_ICON_MAP[normalized] || LayoutGrid;
}
